// Generated by GPT but it's working.

const crypto = require("crypto");

const accessKeyId = process.env.AWS_ACCESS_KEY_ID;
const secretKey = process.env.AWS_SECRET_ACCESS_KEY;
const region = "ap-south-1";
const bucket = "varunmendres3";
const key = "image.webp";
const expires = 3600;

const hmac = (k, d, enc) =>
  crypto.createHmac("sha256", k).update(d, "utf8").digest(enc);
const sha256 = (d) =>
  crypto.createHash("sha256").update(d, "utf8").digest("hex");

const now = new Date();
const amzDate = now.toISOString().replace(/[:-]|\.\d{3}/g, "");
const date = amzDate.slice(0, 8);
const scope = `${date}/${region}/s3/aws4_request`;
const host = `${bucket}.s3.${region}.amazonaws.com`;

const qs = [
  `X-Amz-Algorithm=AWS4-HMAC-SHA256`,
  `X-Amz-Credential=${encodeURIComponent(`${accessKeyId}/${scope}`)}`,
  `X-Amz-Date=${amzDate}`,
  `X-Amz-Expires=${expires}`,
  `X-Amz-SignedHeaders=host`,
]
  .sort()
  .join("&");

const creq = `GET\n/${encodeURIComponent(
  key
)}\n${qs}\nhost:${host}\n\nhost\nUNSIGNED-PAYLOAD`;
const sts = `AWS4-HMAC-SHA256\n${amzDate}\n${scope}\n${sha256(creq)}`;

let k = hmac("AWS4" + secretKey, date);
k = hmac(k, region);
k = hmac(k, "s3");
k = hmac(k, "aws4_request");
const sig = hmac(k, sts, "hex");

console.log(
  `https://${host}/${encodeURIComponent(key)}?${qs}&X-Amz-Signature=${sig}`
);
